## Python Reviewwwwww

Goals: 
- recall basic Pytohon vocab
- practice markdown

#### Libarries and packages
**Library** a scollection of code that we can use to perofm specific tasks in our porgrams. 

**NumPy**
- core library for numerical computing in python 
- many other libarire use NumPy arrays as building blocks
- computations on NumPy are optiomozied for speed and memory usage

Lets import NumPy with Stadnard abreviations

In [2]:
import numpy as np

## Variables 

**variables**: a name we assign to a particular object in Python 

Example: 

In [3]:
# Assign a small array to a variable a 
a = np.array([[1,1,2],[3,5,8]])

In [4]:
#run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use 'print' function ot print the value 
print(a)

[[1 1 2]
 [3 5 8]]


### Objects
**object** (inofrmatlly speaking) is a bundle of *properites* and *actions* about sometihing speicifc.

Example:

Object: data frame 

Preperties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name w e give a specific object, and the same object can be reference by different variables. 

In practice, we can often use vairable and object interchangeably. 