## Python Reviewwwwww

Goals: 
- recall basic Pytohon vocab
- practice markdown

#### Libarries and packages
**Library** a scollection of code that we can use to perofm specific tasks in our porgrams. 

**NumPy**
- core library for numerical computing in python 
- many other libarire use NumPy arrays as building blocks
- computations on NumPy are optiomozied for speed and memory usage

Lets import NumPy with Stadnard abreviations

In [1]:
import numpy as np

## Variables 

**variables**: a name we assign to a particular object in Python 

Example: 

In [2]:
# Assign a small array to a variable a 
a = np.array([[1,1,2],[3,5,8]])

In [3]:
#run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function ot print the value 
print(a)

[[1 1 2]
 [3 5 8]]


### Objects
**object** (inofrmatlly speaking) is a bundle of *properites* and *actions* about sometihing speicifc.

Example:

Object: data frame 

Preperties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name w e give a specific object, and the same object can be reference by different variables. 

In practice, we can often use vairable and object interchangeably. 

## Types

Every object in Python has a **type**. the type tells us what kind of object it is. 
We can also call the type of an object, the **class** of an object and they both mean what kind of object we have. 

In [6]:
print(a)

# check the type/class of a variable/object by using 'type' fucntion
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [7]:
print(a[0,0])

# check the type on an entry on the array by indexing 
type(a[0,0])

1


numpy.int64

Notice that 'type(a[0,0])' is *'numpy.int64'* and not just the standard Python integer type. This is telling us that 1 is an interger stored as a 64-bit number. 

In [8]:
a[1,1]

5

### Functions

'print' was our first example of a *function*

Functions take in a set of **arguments** and those arguments create an **output**
argument = parameter. 

We can ask information about a function by executing *?function* 

In [9]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information (listed above) is a **docstring**

A function has two types of arguments:

- **non-optional argument**: arguments *you* need to specify for the function to do something 

- **optional argument** arguments that are pre-filled with a default value by the funciton. You can override them. Optional arguments appear inside the parenthesis in th eform 'optional argument=defualt_value'

In [10]:
print('changing the default end argument', end= ' :)')

changing the default end argument :)

### Attributes and Methods

An object in Python has atrributes and methods. 

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with the object, an action 

Fish attributes:
-length, color, species, 

Fish methods:
die(), bite(), swim()

**Example**
Attributes for 'numpy.arrays'

We can access a variable's attributes and methods by adding a period '.' at the end of the variable's name.

*'variable.method'* or *'variable.attribute'*

In [11]:
a.shape

(2, 3)

In [12]:
type(a.shape)

tuple

In [13]:
#Methods examples
# min() returs the minimum value along a specified axis
a.min(axis=0)

array([1, 1, 2])

## Check-In
We can also call the **min** method without any parameters

In [14]:
a.min()

1

Remember: methods are function associated with an object. 

In [15]:
type(a.min)

builtin_function_or_method

### Exercise

1. Read teh 'print' function help. What is the **type** of the argument 'sep'? Is this an optional or non-optional argument? Why? 
builtin_function_or_method, optional (because it has a default reading), its a string (it says so, and has quotes)

2. Create two new variables, one with the interger value 77 and another one with the string 99. 
x = 77
y = '99'

3. Use your variables to print '77%99%77' by changing the value of one of hte optional arguments in 'print'
print('x,y,x' sep='%')

In [28]:
x = 77
y = '99'
print(x,y,x, sep='%')

77%99%77


In [22]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method